Lesson7
nat0t/django_basic pull request #7
Opened 2021-03-16 19:15 UTC by nat0t

ДЗ к уроку №7.
Имею вопрос:
https://github.com/nat0t/django_basic/blob/405382d34c9978ca195845c82e17d2ed7894223b/adminapp/forms.py#L47
В этой строке я присваиваю элементам формы класс, но он почему-то не применяется в вёрстке. Не смог разобраться почему.

2021-03-17 16:43 UTC, Vokler requested changes

2021-03-17 16:43 UTC, Vokler commented on adminapp/forms.py
> +        def __init__(self, *args, **kwargs):
У вас `__init__()` тут к классе `Meta`, а должен быть к `ProductAdminCreationForm`. Скорее из-за этого и ошибка

2021-03-18 03:47 UTC, nat0t commented on adminapp/forms.py
> +        def __init__(self, *args, **kwargs):
Действительно, был невнимателен и метод __init__ оказался в метаклассе. Исправил и теперь всё прекрасно работает. Благодарю!

2021-03-18 12:30 UTC, Vokler approved these changes

2021-03-18 12:30 UTC, merged